# log:
#   level: DEBUG

api:
  debug: true
  insecure: true

# entryPoints:
#   web:
#     address: :80

# providers:
#   docker:
    # swarmMode: true
    # watch: true
    # network: cluster_network
    # exposedbydefault: false
    # endpoint: unix://var/run/docker.sock
